version: '3'

services:
  db: 
    image: mysql:8.4
    restart: always
    ports: 
      - "3307:3306"
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    container_name: tu-blog
    volumes:
      - ./mysql_data:/var/lib/info
